import type { Topic } from "./types";

export const topics: Topic[] = [
  {
    id: "data-structure",
    title: "資料結構",
    stage: 0,
    tagline: "資料的「收納方式」——決定你找東西快不快",
    notTaught: ["時間複雜度 Big-O", "平衡樹細節", "演算法競賽技巧"],
    prerequisites: [],
    position: { x: 0, y: 0 },
    steps: [
      {
        type: "analogy",
        title: "比喻：收納方式",
        body: "資料結構就像家裡的收納方式——抽屜、櫃子、族譜樹，決定你找東西快不快。同一批東西，收納方式不同，找起來的速度天差地遠。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "陣列 / 清單：一排編號的置物櫃，依號碼找東西",
          "Key-Value：貼標籤的箱子，例如字典，用「名字」找內容",
          "樹狀結構：家族族譜、資料夾巢狀結構，一層包一層",
          "為什麼「結構選對」查詢會變快：翻書 vs 翻字典的差別",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "如果你要做一本「通訊錄」，用姓名快速查電話，比較適合用哪種收納方式？",
        options: ["按登記順序排的清單", "用姓名當標籤的 Key-Value", "沒有規則的散亂堆放"],
        correctIndex: 1,
        explanation: "用姓名當 Key 直接對應到電話，就像字典一樣可以快速查到，不用整本翻過一遍。",
      },
    ],
  },
  {
    id: "networking",
    title: "網路傳輸",
    stage: 0,
    tagline: "兩台電腦怎麼「對話」？",
    notTaught: ["TCP 三向交握細節", "OSI 七層模型全部背誦", "封包格式"],
    prerequisites: [],
    position: { x: 0, y: 260 },
    steps: [
      {
        type: "analogy",
        title: "比喻：打電話",
        body: "兩台電腦對話就像兩個人打電話——要有「電話號碼」（IP）、「分機」（Port），還要講同一種語言（協定），對方才聽得懂。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "IP：電腦在網路上的地址",
          "Port：同一台電腦裡，不同服務的「分機號碼」",
          "Client-Server：誰先開口發請求、誰負責回應",
          "HTTP 是一種「對話規則」，不是網路本身",
          "TCP（掛號信，保證送達）vs UDP（普通信，快但不保證）",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "網址 http://example.com:8080 裡的「8080」代表什麼？",
        options: ["網站的密碼", "分機號碼（Port）", "檔案的版本號"],
        correctIndex: 1,
        explanation: "8080 是 Port，代表要連到這台主機上「哪一個服務」，就像打電話轉分機一樣。",
      },
    ],
  },
  {
    id: "sql",
    title: "SQL / 資料庫",
    stage: 1,
    tagline: "一個很會整理的 Excel 系統",
    notTaught: ["正規化理論", "交易隔離等級", "索引優化細節"],
    prerequisites: ["data-structure"],
    position: { x: 300, y: 0 },
    steps: [
      {
        type: "analogy",
        title: "比喻：進階版 Excel",
        body: "資料庫就是「一個很會整理的 Excel 系統」，SQL 是你跟它下指令的語言，讓它幫你新增、查詢、修改、刪除資料。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "Table / 欄位 / 資料列：就是進階版的 Excel 表格",
          "CRUD：新增（INSERT）、查詢（SELECT）、修改（UPDATE）、刪除（DELETE）",
          "主鍵：每個人的身分證字號，不會重複，用來認出「是哪一列」",
          "表格關聯 JOIN：訂單表 連到 客戶表，把兩張表格「拼」在一起看",
          "GROUP BY / COUNT：分組統計，例如「每個客戶各下了幾張訂單」",
          "NULL：代表「沒有值」，跟空字串或 0 不一樣，QA 測試資料缺漏時常會遇到",
        ],
      },
      {
        type: "concept",
        title: "SQL 基本語法小抄",
        bullets: [
          "查詢：SELECT 欄位1, 欄位2 FROM 表格名 WHERE 條件; — 例如 SELECT title, stock FROM books WHERE stock < 10;",
          "新增：INSERT INTO 表格名 (欄位1, 欄位2) VALUES (值1, 值2); — 例如 INSERT INTO books (title, stock) VALUES ('新書', 10);",
          "修改：UPDATE 表格名 SET 欄位 = 新值 WHERE 條件; — 一定要加 WHERE，不然整張表的資料都會被改掉",
          "刪除：DELETE FROM 表格名 WHERE 條件; — 同樣要小心 WHERE，沒加會把整張表清空",
          "WHERE 條件：可以用 =、!=、<、>、AND、OR 組合，篩出更精確的資料範圍",
          "排序與限制筆數：ORDER BY 欄位 DESC 由大到小排序、LIMIT 數字 只取前幾筆結果",
          "分組統計：GROUP BY 欄位 搭配 COUNT(*) / SUM(欄位) / AVG(欄位) 等聚合函式，把資料依欄位值分組後各自統計；例如 SELECT customer_id, COUNT(*) FROM orders GROUP BY customer_id; 可以算出每位客戶各下了幾張訂單",
          "篩選分組結果：GROUP BY 之後要再篩選統計結果（例如「只看訂單數超過 2 筆的客戶」）要用 HAVING，而不是 WHERE，因為 WHERE 是篩選分組前的原始資料列",
        ],
      },
      {
        type: "sql-sandbox",
        title: "動手試試：真的跑一次 SQL",
        body: "下面切換不同情境練習：書店庫存的基本查詢、訂單與客戶的跨表 JOIN，以及專門給 QA 練習的邊界值／NULL 情境。每個情境都完整列出目前的資料表內容，並準備了 SELECT / INSERT / UPDATE / DELETE 四種練習題，執行後可以直接看到資料表被新增、修改、刪除的結果。",
      },
      {
        type: "quiz",
        title: "小驗收 1：基本查詢",
        question: "想要「查出所有書名」，該用哪個指令開頭？",
        options: ["SELECT", "INSERT", "DELETE"],
        correctIndex: 0,
        explanation: "SELECT 用來查詢資料，INSERT 是新增、DELETE 是刪除。",
      },
      {
        type: "quiz",
        title: "小驗收 2：跨表查詢情境",
        question: "在「訂單與客戶」情境中，想要同時顯示「客戶姓名」和「訂了哪本書」，因為這兩個欄位分別在 customers 和 orders 兩張表格裡，該用哪個關鍵字把它們接起來？",
        options: ["JOIN", "GROUP BY", "LIMIT"],
        correctIndex: 0,
        explanation: "JOIN 可以依照關聯欄位（例如 customer_id）把兩張表格的資料「拼」在一起查詢。",
      },
      {
        type: "quiz",
        title: "小驗收 3：QA 邊界值情境",
        question: "在「邊界值與 NULL」情境中，如果規格寫「年齡必須大於等於 18 歲」，身為 QA 最應該優先測試的資料是哪一筆？",
        options: [
          "年齡 = 30（明顯合法的一般值）",
          "年齡 = 18（剛好卡在規則邊界上）",
          "年齡 = 999（明顯超出常理的極端值）",
        ],
        correctIndex: 1,
        explanation: "邊界值分析告訴我們，規則的「邊界」（這裡是剛好等於 18）最容易因為程式寫成 > 而不是 >= 而出現 bug，是 QA 測試的重點。",
      },
      {
        type: "quiz",
        title: "小驗收 4：CRUD 語法",
        question: "顧客要求「把某本書的庫存扣掉 1（代表賣出一本）」，應該用哪個指令開頭？",
        options: ["INSERT", "UPDATE", "DELETE"],
        correctIndex: 1,
        explanation: "UPDATE 是修改既有資料列的值；INSERT 是新增一筆全新的資料，DELETE 則是整筆刪掉，這裡只是要改動庫存數字，所以是 UPDATE。",
      },
    ],
  },
  {
    id: "linux",
    title: "Linux",
    stage: 2,
    tagline: "另一種作業系統，只是改用打字下指令",
    notTaught: ["Shell script 進階語法", "核心（kernel）原理", "系統管理"],
    prerequisites: [],
    position: { x: 300, y: 260 },
    steps: [
      {
        type: "analogy",
        title: "比喻：打字版的檔案總管",
        body: "Linux 就是「另一種作業系統」，沒有滑鼠點點點，改用打字下指令。Terminal 就是「打字版的檔案總管」。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "為什麼工程師常用 Linux：伺服器幾乎都跑 Linux",
          "基本指令：ls（列出檔案）、cd（切換資料夾）、pwd（目前在哪）、cat（看檔案內容）、mkdir（新增資料夾）",
          "檔案權限：誰可以看 / 改 / 執行，用「鑰匙」比喻",
        ],
      },
      {
        type: "linux-sandbox",
        title: "動手試試：模擬終端機",
        body: "下面是一個模擬的終端機，已經幫你準備好 /home/user 底下的檔案。試著用指令探索看看。",
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "指令 mkdir project && cd project 在做什麼？",
        options: [
          "刪除 project 資料夾",
          "新增一個叫 project 的資料夾，然後切換進去",
          "列出 project 資料夾內容",
        ],
        correctIndex: 1,
        explanation: "mkdir 新增資料夾，&& 代表「前一步成功才繼續」，cd 是切換進去該資料夾。",
      },
    ],
  },

  {
    id: "docker",
    title: "Docker",
    stage: 2,
    tagline: "隨身攜帶的完整房間",
    notTaught: ["Docker Compose 進階編排", "Kubernetes", "網路模式細節"],
    prerequisites: ["linux"],
    position: { x: 600, y: 260 },
    steps: [
      {
        type: "analogy",
        title: "比喻：隨身攜帶的房間",
        body: "Docker 就是「隨身攜帶的完整房間」——不管搬到誰的電腦，房間裡的擺設（環境）都一樣，不會出現「在我電腦可以跑，換一台就壞掉」的問題。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "為什麼需要它：解決「環境不一致」的痛點",
          "Image：房間的設計圖（不會變動）",
          "Container：真的蓋出來、正在運作的房間",
          "常用指令：docker run（蓋房間並住進去）、docker ps（看有哪些房間在運作）、docker stop（把房間關掉）",
          "Dockerfile：蓋房間的施工說明書",
        ],
      },
      {
        type: "docker-visual",
        title: "圖解：從 Dockerfile 到 Container",
        body: "點下面每個方塊看說明，也可以展開「有沒有 Docker」的比較圖。",
      },
      {
        type: "docker-sandbox",
        title: "動手試試：模擬 docker 指令列",
        body: "已經幫你準備好一個 nginx:latest 的 image，試著把它跑成容器、看看有哪些容器在運作、再把它停掉並刪除，體驗一次完整的 build → run → stop → rm 流程。",
      },
      {
        type: "quiz",
        title: "小驗收 1",
        question: "Image 跟 Container 的差別，比較接近下面哪一個說法？",
        options: [
          "Image 是設計圖，Container 是照圖蓋出來、正在運作的房間",
          "兩者是同一件事，只是名字不同",
          "Container 是設計圖，Image 是蓋好的房間",
        ],
        correctIndex: 0,
        explanation: "Image 不會變動，是「藍圖」；Container 是根據 Image 實際跑起來的實體。",
      },
      {
        type: "quiz",
        title: "小驗收 2：指令情境",
        question: "已經有一個叫 myapp 的容器正在背景執行（docker run -d），想要暫時把它關掉但不刪除，之後還能再啟動回來，該用哪個指令？",
        options: ["docker rm myapp", "docker stop myapp", "docker rmi myapp"],
        correctIndex: 1,
        explanation: "docker stop 只是把容器關掉（狀態變成 exited），容器本身還在，之後可以用 docker start 再次啟動；docker rm 才是真正把容器刪除。",
      },
      {
        type: "quiz",
        title: "小驗收 3：常見錯誤",
        question: "如果直接對一個「正在執行中」的容器下 docker rm，實際的 docker 會怎麼回應？",
        options: [
          "直接刪除，沒有任何限制",
          "拒絕刪除，要求先 docker stop 把容器停掉，或加上 -f 強制刪除",
          "自動先幫你執行 docker stop 再刪除",
        ],
        correctIndex: 1,
        explanation: "docker 預設不會讓你刪除還在執行中的容器，這是保護機制，避免不小心刪掉正在服務中的容器；要嘛先 stop，要嘛加 -f 強制刪除。",
      },
    ],
  },
  {
    id: "rest-api",
    title: "RESTful API",
    stage: 3,
    tagline: "餐廳菜單——照著點餐，廚房就會出餐",
    notTaught: ["GraphQL", "API 版本控制策略", "OAuth 完整規格"],
    prerequisites: ["networking", "sql"],
    position: { x: 600, y: 0 },
    steps: [
      {
        type: "analogy",
        title: "比喻：餐廳菜單",
        body: "API 就是「餐廳菜單」——你不用進廚房，只要照著菜單點餐（發請求），廚房就會出餐（回應資料）。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "Request / Response：請求要有方法、網址、資料；回應會有結果",
          "GET / POST / PUT / DELETE 對應「查、增、改、刪」，跟 SQL 的 CRUD 是同一件事的不同說法",
          "Status Code：200（成功）、404（找不到）、500（伺服器出錯），像服務生的回覆",
          "JSON：資料的共同語言格式，讓不同系統都看得懂",
        ],
      },
      {
        type: "api-sandbox",
        title: "動手試試：呼叫一個模擬 API",
        body: "下面是一個「書店 API」，新增／修改／刪除都會真的改動資料（不是假的），操作後可以再查一次全部書籍確認結果。",
      },
      {
        type: "quiz",
        title: "小驗收 1",
        question: "呼叫 API 後收到 Status Code 404，代表什麼？",
        options: ["請求成功", "找不到你要的資源", "伺服器內部發生錯誤"],
        correctIndex: 1,
        explanation: "404 代表「找不到」，通常是網址或資源 ID 不存在；500 才是伺服器自己出錯。",
      },
      {
        type: "quiz",
        title: "小驗收 2：驗證資料真的變了",
        question: "呼叫 POST /books 新增一本書後，收到 Status 201 且回應內容看起來正確，身為 QA 接下來最應該做什麼？",
        options: [
          "相信回應內容就好，不用再確認",
          "再呼叫一次 GET /books，確認新資料真的被存起來、筆數真的增加",
          "直接判斷這支 API 沒有問題並結案",
        ],
        correctIndex: 1,
        explanation: "API 的回應只代表「伺服器說它做了」，QA 測試時應該再查詢一次驗證資料確實被持久化，這是很多真實 bug（回應成功但資料沒真的寫入）會被抓到的關鍵習慣。",
      },
    ],
  },
  {
    id: "message-queue",
    title: "資料佇列 / MQ",
    stage: 4,
    tagline: "銀行的排隊叫號機",
    notTaught: ["Kafka 分區機制", "訊息保證語意細節", "叢集架構"],
    prerequisites: ["rest-api", "docker"],
    position: { x: 900, y: 130 },
    steps: [
      {
        type: "analogy",
        title: "比喻：排隊叫號機",
        body: "資料佇列就是「銀行的排隊叫號機」——客人（請求）不用一直站著等櫃檯處理完，先抽號碼牌，系統會照順序慢慢處理。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "為什麼需要它：同步請求太慢、系統忙不過來時的解法",
          "Producer（發號碼牌的人）/ Consumer（櫃檯）/ Queue（排隊隊伍）",
          "「非同步」：先做別的事，等通知再回來處理",
          "ACK（確認收到）：Consumer 處理完要跟佇列回報一聲，佇列才會真的刪掉這則訊息",
          "常見場景：訂單處理、寄送通知信",
        ],
      },
      {
        type: "mq-visual",
        title: "圖解：排隊動畫",
        body: "連續按幾次「送出新請求」，看看號碼牌怎麼排隊、怎麼被一個一個處理掉。",
      },
      {
        type: "mq-failure-visual",
        title: "圖解：Consumer 突然掛掉，訊息會不見嗎？",
        body: "一步一步看：處理到一半的 Consumer 當機了，佇列怎麼確保這則訊息還是會被處理完成，不會憑空消失。",
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "網路購物「付款後立刻跳成功頁面，出貨通知信晚點才寄到」，比較像哪種模式？",
        options: ["同步，馬上處理完才給結果", "非同步排隊，之後再慢慢處理", "沒有任何處理"],
        correctIndex: 1,
        explanation: "付款結果馬上給你，但寄信這種「不急著馬上完成」的事會被丟進佇列，之後再慢慢處理。",
      },
    ],
  },
  {
    id: "test-case-design",
    title: "測試案例設計",
    stage: 5,
    tagline: "把「憑感覺測」變成「有系統地測」",
    notTaught: ["形式化驗證方法", "測試案例管理系統操作細節", "模型驅動測試工具鏈"],
    prerequisites: [],
    position: { x: 0, y: 520 },
    steps: [
      {
        type: "analogy",
        title: "比喻：衣服的尺碼表",
        body: "衣服不會每個身高、體重都做一件，而是分成 S / M / L 幾個「等價」的區間，各區間內隨便挑一個人試穿都差不多準。測試案例設計也一樣：與其把每種輸入都測一遍，不如先把輸入分類，每一類挑代表性的值，並特別留意「剛好卡在分類邊界」的那幾件。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "等價分割（Equivalence Partitioning）：把輸入依「行為是否相同」分組，每組只需測一個代表值",
          "邊界值分析（Boundary Value Analysis）：規則的邊界（剛好等於、剛好差一）最容易寫錯，例如 >= 18 寫成 > 18",
          "決策表（Decision Table）：當有多個條件互相組合時，用表格列出「條件組合 → 應該發生的結果」，避免漏掉某種組合",
          "Given-When-Then：用「情境 / 動作 / 結果」描述一個案例，讓不懂程式的人也能看懂測試在驗證什麼",
        ],
      },
      {
        type: "quiz",
        title: "小驗收 1：邊界值",
        question: "系統規則是「訂單金額滿 1000 元免運費」，用邊界值分析，最值得測試的金額組合是？",
        options: [
          "500 元、5000 元（一個很小、一個很大）",
          "999 元、1000 元、1001 元（剛好卡在邊界前後）",
          "只測 1000 元一種就夠了",
        ],
        correctIndex: 1,
        explanation: "999、1000、1001 剛好涵蓋「差一點沒到」「剛好達到」「超過」三種邊界情況，最容易抓出 > 寫成 >= 之類的錯誤。",
      },
      {
        type: "quiz",
        title: "小驗收 2：等價分割",
        question: "一個欄位規定「只能輸入 1~100 的整數」，下面哪一組測試資料最符合「等價分割」的精神？",
        options: [
          "1, 2, 3, 4, 5……一路測到 100（每個數字都測）",
          "50（合法區間的代表值）、0（太小）、101（太大）、abc（非數字）",
          "只測一個 50 就結束",
        ],
        correctIndex: 1,
        explanation: "等價分割是每種「類別」各挑一個代表值：合法範圍內、小於下限、大於上限、格式錯誤，四個代表值就能涵蓋主要情境，不需要窮舉每個數字。",
      },
    ],
  },
  {
    id: "bug-lifecycle",
    title: "缺陷生命週期與管理",
    stage: 5,
    tagline: "一張罰單從開單到結案的旅程",
    notTaught: ["特定工具（Jira/Zentao）操作介面細節", "SLA 罰則計算", "跨團隊流程治理制度"],
    prerequisites: [],
    position: { x: 300, y: 520 },
    steps: [
      {
        type: "analogy",
        title: "比喻：一張罰單的旅程",
        body: "回報一個 bug 就像開一張罰單：先「開單」記錄現場（重現步驟），交給對的人「處理」，處理完要有人「驗證」真的改好了才能「結案」；如果驗證沒過，罰單會被「退回」重開一輪，不是隨便關掉就算了。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "缺陷狀態流轉：New（新開） → In Progress（處理中） → Resolved（已修復） → Verified/Closed（驗證通過關閉）或 Reopened（驗證沒過，退回重修）",
          "Severity（嚴重程度）：這個 bug 造成的影響有多嚴重（例如系統當機 vs 文字對不齊）",
          "Priority（優先權）：這個 bug 該多快被處理（可能嚴重度不高，但影響到重要客戶，優先權就拉高）",
          "重現步驟（Repro Steps）：清楚寫出「怎麼操作會發生」，是 bug 能不能被修好的關鍵，比一句「壞了」有用一百倍",
          "為什麼要記錄環境資訊：同一個 bug 可能只在特定瀏覽器、特定資料狀態下才會出現",
        ],
      },
      {
        type: "quiz",
        title: "小驗收 1：Severity vs Priority",
        question: "「登入頁面某個按鈕的文字對齊有 2px 的小誤差，但這個功能是本週要展示給重要客戶看的」，這種情況比較符合下面哪種分類？",
        options: [
          "Severity 高、Priority 高",
          "Severity 低、Priority 高",
          "Severity 高、Priority 低",
        ],
        correctIndex: 1,
        explanation: "這個瑕疵本身對系統功能影響很小（Severity 低），但因為時機敏感、需要盡快修（Priority 高），這正是 Severity 跟 Priority 會不一致的典型例子。",
      },
      {
        type: "quiz",
        title: "小驗收 2：驗證與 Reopen",
        question: "開發說某個 bug 已經修好並改成 Resolved，QA 重新測試後發現在特定情況下問題還是會發生，接下來該怎麼做？",
        options: [
          "直接把狀態改成 Closed，反正大部分情況都正常了",
          "把狀態改回 Reopened，並補充「還會發生問題」的具體重現條件",
          "自己私下修掉就好，不需要更新狀態",
        ],
        correctIndex: 1,
        explanation: "驗證沒通過就該 Reopen，並且補上新的重現條件讓開發知道差在哪裡，狀態要誠實反映真實情況，才能讓整個團隊追蹤進度。",
      },
    ],
  },
  {
    id: "api-testing",
    title: "API 測試實務",
    stage: 5,
    tagline: "試菜員不只吃合格套餐，也要故意點奇怪組合",
    notTaught: ["Postman 進階功能（Collection Runner、Newman CI 整合）", "RestAssured 完整語法", "API 安全滲透測試細節", "GraphQL 測試"],
    prerequisites: ["rest-api"],
    position: { x: 600, y: 520 },
    steps: [
      {
        type: "analogy",
        title: "比喻：試菜員",
        body: "API 測試就像餐廳的試菜員——不能只點菜單上寫好的正常套餐（正向案例），還要故意點「沒有的菜」「數量填負的」「不付錢就要出餐」，看廚房會不會端出奇怪的東西，或至少要有禮貌地說「做不到」（正確的錯誤回應），而不是當場爆炸（500 錯誤、系統當機）。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "正向案例（Happy Path）：照規格正常操作，應該要成功",
          "反向案例（Negative Case）：故意給錯誤的輸入（缺欄位、型別錯、超出範圍），驗證系統有沒有「優雅地拒絕」而不是壞掉",
          "驗證重點不只是 Status Code：回應的 Schema（欄位有沒有齊全、型別對不對）、回應時間、資料是否真的被寫入，都是驗證項目",
          "契約測試（Contract Testing）：確保 API 的輸入輸出格式跟前端 / 其他服務約定的規格一致，避免「後端改格式，前端就壞掉」",
          "Mock Server：當依賴的第三方 API 還沒好、或不想每次測試都打真實服務時，用假伺服器模擬固定的回應",
        ],
      },
      {
        type: "api-sandbox",
        title: "動手試試：用 QA 的角度操作這支 API",
        body: "試著故意送出不合法的 body（例如缺少 title、stock 給字串），觀察 API 有沒有回傳正確的 400 錯誤，而不是直接壞掉或吃掉錯誤資料。",
      },
      {
        type: "concept",
        title: "Postman Tests 腳本小抄",
        bullets: [
          "pm.test(\"測試名稱\", function () { ... })：定義一個測試案例，裡面斷言全部通過才算這個案例通過，失敗會各自獨立記錄，不會互相影響",
          "pm.response.to.have.status(200)：斷言這次回應的狀態碼是不是預期的數字，最常用的第一道檢查",
          "pm.response.json()：把回應 body 解析成 JS 物件/陣列，方便進一步檢查裡面的欄位",
          "pm.expect(值).to.xxx：Chai 風格斷言，常用的有 .to.eql(期望值)（整個比對）、.to.have.property(\"欄位名\")（有沒有這個欄位）、.to.be.a(\"array\")（型別對不對）、.to.include(值)（陣列或字串裡有沒有包含）",
          "pm.response.responseTime：這次請求花了幾毫秒，可以用 .to.be.below(1000) 這類寫法做簡單的效能斷言",
          "{{變數名稱}}：Environment / Collection 變數的插值語法，同一份請求只要切換變數值（例如 base_url），就能打不同環境，不用每次改網址",
        ],
      },
      {
        type: "postman-sandbox",
        title: "動手試試：寫一段 Postman 風格的 Tests 腳本",
        body: "簡化版的 Postman 練習：Path 支援 {{base_url}} 這種 Environment 變數，送出請求後會自動執行 Tests 腳本（跟真正 Postman 的 pm.test / pm.expect 語法一致），下方會顯示每項斷言是通過還是失敗。",
      },
      {
        type: "quiz",
        title: "小驗收 1",
        question: "測試「新增書籍」的 API 時，下面哪一個比較屬於「反向案例」？",
        options: [
          "帶正確的 title 和 stock，預期成功新增",
          "完全不帶 title 欄位，預期收到 400 且清楚的錯誤訊息",
          "查詢一本已存在的書，預期回傳該書資料",
        ],
        correctIndex: 1,
        explanation: "反向案例是刻意給不合法或不完整的輸入，重點在驗證系統有沒有「正確地拒絕」，而不是驗證正常流程。",
      },
      {
        type: "quiz",
        title: "小驗收 2：Postman 斷言",
        question: "在 Postman 的 Tests 腳本中，想要驗證「回應狀態碼是 200」，該用下面哪一行寫法？",
        options: [
          "pm.response.to.have.status(200);",
          "pm.request.setStatus(200);",
          "pm.environment.set(\"status\", 200);",
        ],
        correctIndex: 0,
        explanation: "pm.response.to.have.status(200) 是 Postman 內建的斷言寫法，用來檢查這次回應的狀態碼是不是 200；pm.environment.set 是用來設定變數，不是拿來斷言的。",
      },
    ],
  },
  {
    id: "test-automation",
    title: "自動化測試與 CI 整合",
    stage: 5,
    tagline: "請一個不會累的機器人幫你重複跑迴歸測試",
    notTaught: ["特定框架（Selenium/Playwright）完整 API", "跨瀏覽器雲端服務比較", "Page Object 進階設計模式"],
    prerequisites: ["api-testing", "docker"],
    position: { x: 900, y: 520 },
    steps: [
      {
        type: "analogy",
        title: "比喻：不會累的機器人",
        body: "自動化測試就像請一個不會累、不會分心、不會抱怨「這個流程我已經點過一百次了」的機器人，每次程式一有變動，就把該重複驗證的流程整套跑一遍，人力則專心去找機器人還想不到的奇怪情境。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "什麼案例適合自動化：會被重複執行、步驟穩定、驗證高風險核心流程的案例；一次性或常常改版的畫面不一定划算",
          "測試金字塔：Unit（單元測試）數量最多、跑最快；Integration（整合測試）居中；E2E（端對端）數量最少、跑最慢但最貼近真實使用情境",
          "CI/CD 整合：每次有人提交程式碼，管線（Pipeline）就自動跑一次測試，及早發現問題，不用等到快發版才手動測",
          "Flaky Test（不穩定測試）：同樣的程式碼，測試有時候過、有時候沒過，通常是等待時間沒抓好或測試之間互相影響，是自動化測試最惱人的問題之一",
        ],
      },
      {
        type: "concept",
        title: "CI/CD 常見工具與平台",
        bullets: [
          "GitHub Actions：跟 GitHub repo 整合最緊密，用 YAML 寫 workflow，社群現成的 action 很多，中小型專案很常見",
          "GitLab CI/CD：內建在 GitLab 裡，用 .gitlab-ci.yml 定義 pipeline 的各個 stage，跟 GitLab 的 Merge Request 流程整合度高",
          "Jenkins：老牌、可自行架設在自己的機器上，外掛生態系最龐大、彈性最高，代價是要自己維運升級",
          "CircleCI：以雲端服務為主，設定相對簡單，新創與中小型團隊常用",
          "Azure DevOps Pipelines：微軟生態系，跟 Azure Repos／Boards 整合，企業內部常見",
          "共通概念：Pipeline（整條流程）由多個 Stage／Job 組成，實際任務交給 Runner／Agent 執行；跑完的建置產物叫 Artifact，重複安裝的套件可以用 Cache 加速",
          "常見做法是把測試跑在 Docker container 裡（呼應前面學過的 Docker），確保跟正式環境的環境一致，不會出現「本機過、CI 卻壞掉」的落差",
        ],
      },
      {
        type: "quiz",
        title: "小驗收 1：測試金字塔",
        question: "測試金字塔的概念建議，一個健康的測試組合應該長怎樣？",
        options: [
          "大量的 E2E 測試，少量的單元測試",
          "大量的單元測試打底，少量但關鍵的 E2E 測試在最上層",
          "只需要 E2E 測試，其他都不需要",
        ],
        correctIndex: 1,
        explanation: "單元測試跑得快、成本低，適合大量覆蓋細節邏輯；E2E 測試貼近真實情境但跑得慢、維護成本高，只留給最關鍵的核心流程。",
      },
      {
        type: "quiz",
        title: "小驗收 2：Flaky Test",
        question: "同一支自動化測試，同樣的程式碼，這次跑過、下次跑失敗，重跑幾次又過了，這種情況最可能是什麼問題？",
        options: [
          "程式碼一定有 bug，且很嚴重",
          "測試本身不穩定（Flaky），可能是等待時間沒設好或測試互相干擾",
          "這是正常現象，不用理它",
        ],
        correctIndex: 1,
        explanation: "結果忽好忽壞、跟程式碼變動無關，通常代表測試本身「不穩定」，需要找出根本原因（例如非同步等待、測試資料污染），而不是單純重跑到過為止。",
      },
    ],
  },
  {
    id: "performance-testing",
    title: "效能測試",
    stage: 5,
    tagline: "尖峰時段的排隊名店，能撐住多少人潮？",
    notTaught: ["JMeter/Gatling 完整腳本語法", "APM 工具深度設定", "容量規劃精算模型"],
    prerequisites: ["message-queue"],
    position: { x: 1200, y: 260 },
    steps: [
      {
        type: "analogy",
        title: "比喻：排隊名店的尖峰時段",
        body: "效能測試就像故意在店家「平常」「特別多人的尖峰時段」「突然湧入一大群人」時，分別去觀察它能不能撐住——出餐會不會變慢、會不會直接當機、人潮退去後能不能恢復正常。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "負載測試（Load Testing）：模擬「平常」預期的使用量，確認系統穩定運作",
          "壓力測試（Stress Testing）：不斷加大流量，直到系統撐不住為止，找出系統的極限在哪",
          "尖峰測試（Spike Testing）：模擬流量突然暴增（例如搶購活動），觀察系統反應",
          "耐久測試（Soak Testing）：長時間維持一定負載，抓「跑久了才會出現」的問題，例如記憶體洩漏",
          "常見指標：回應時間（Response Time）、吞吐量（Throughput，單位時間處理幾筆）、錯誤率（Error Rate）",
          "瓶頸可能藏在哪裡：應用程式本身、資料庫查詢、網路頻寬，或是訊息佇列堆積來不及消化",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "電商平台想知道「雙11搶購開賣那一秒瞬間湧入十倍平常流量，系統會不會撐不住」，這比較接近哪一種效能測試？",
        options: ["耐久測試（Soak Testing）", "尖峰測試（Spike Testing）", "只需要一般的功能測試"],
        correctIndex: 1,
        explanation: "「瞬間暴增」的流量情境正是尖峰測試要驗證的重點，跟耐久測試（長時間穩定負載）觀察的問題不一樣。",
      },
    ],
  },
  {
    id: "data-structure-advanced",
    title: "資料結構進階",
    stage: 6,
    tagline: "同樣找得到，但快很多還是慢很多？",
    notTaught: ["各種平衡樹的旋轉演算法證明", "演算法競賽技巧與模板", "攤還分析（Amortized Analysis）"],
    prerequisites: ["data-structure"],
    position: { x: 0, y: 780 },
    steps: [
      {
        type: "concept",
        title: "進階概念",
        bullets: [
          "Big-O 是什麼：用「輸入資料變大時，操作次數大概怎麼成長」描述效能，例如 O(1)、O(log n)、O(n)、O(n²)，是成長趨勢而不是精確秒數",
          "為什麼要懂一點 Big-O：系統「資料量一變大就變慢很多」，往往是用了 O(n²) 或更差的演算法/查詢方式，這是效能問題常見的根因",
          "平衡樹（例如 AVL Tree、紅黑樹）：一般二元樹如果資料剛好照順序塞進去，會退化成一條「鏈」，查詢變成 O(n)；平衡樹會自動調整結構維持左右高度接近，確保查詢維持在 O(log n)",
          "資料庫索引背後常是變形的平衡樹（如 B-Tree/B+Tree），這也是為什麼有加索引的查詢通常比全表掃描快很多",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "一個網站資料量成長到 10 萬筆後，查詢速度變慢的幅度遠超過資料量成長的比例，最可能的原因？",
        options: ["用了效能較差的演算法或查詢方式（例如 O(n²)）", "伺服器記憶體不足", "網路頻寬不夠"],
        correctIndex: 0,
        explanation: "查詢時間隨資料量增加而不成比例地暴增，通常代表用了效能較差的演算法/查詢方式，這正是複雜度概念要處理的問題。",
      },
    ],
  },
  {
    id: "networking-advanced",
    title: "網路傳輸進階",
    stage: 6,
    tagline: "電話接通前，其實先握了三次手",
    notTaught: ["TCP 壅塞控制演算法細節", "IPv6 位址規劃", "Wireshark 實際操作教學"],
    prerequisites: ["networking"],
    position: { x: 300, y: 780 },
    steps: [
      {
        type: "concept",
        title: "進階概念",
        bullets: [
          "TCP 三向交握（Three-way Handshake）：SYN → SYN-ACK → ACK，雙方先確認「你聽得到我、我聽得到你」才正式開始傳資料，這也是為什麼建立連線會有一點延遲",
          "為什麼需要交握：確保雙方都準備好、同步序號，避免舊封包或不同步造成資料錯亂",
          "OSI 七層模型：由下到上依序是實體層、資料鏈結層、網路層、傳輸層、會議層、表現層、應用層；實務上最常打交道的是網路層（IP）、傳輸層（TCP/UDP）、應用層（HTTP 等）",
          "封包格式：一個封包大致上有 Header（裝址地址、序號等控制資訊）跟 Payload（實際要傳的資料），就像信封（Header）裝著信件內容（Payload）",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "TCP 為什麼要先做三向交握，而不是直接開始傳資料？",
        options: [
          "確保雙方都準備好且同步序號，避免資料錯亂或遺失",
          "純粹是歷史包袱，沒有實際作用",
          "讓網路速度加快",
        ],
        correctIndex: 0,
        explanation: "三向交握讓雙方先確認彼此的傳送/接收能力與初始序號，這是 TCP「可靠傳輸」的基礎之一。",
      },
    ],
  },
  {
    id: "sql-advanced",
    title: "SQL 進階",
    stage: 6,
    tagline: "資料庫也要「斷捨離」，還要學會排隊等鎖",
    notTaught: ["各資料庫廠商的鎖定機制實作差異", "執行計畫（Execution Plan）分析", "分散式交易（2PC）"],
    prerequisites: ["sql"],
    position: { x: 600, y: 780 },
    steps: [
      {
        type: "concept",
        title: "進階概念",
        bullets: [
          "正規化（Normalization）：把資料拆成多張表格、減少重複儲存的設計方法，常聽到的第一/第二/第三正規化（1NF/2NF/3NF）就是不同程度的拆分規則，目的是避免同一筆資料散落各處、改一個地方卻忘了改別的地方",
          "交易（Transaction）：把好幾個 SQL 操作包成一組，要嘛全部成功、要嘛全部復原（Rollback），例如轉帳要同時扣款方和收款方都成功，不能只扣一半",
          "交易隔離等級（Isolation Level）：多個交易同時進行時，彼此看不看得到對方「還沒 commit」的資料，由寬鬆到嚴格依序是 Read Uncommitted、Read Committed、Repeatable Read、Serializable，越嚴格越安全但效能越差",
          "索引優化：加索引能加速查詢，但索引太多會拖慢新增/修改/刪除的速度（因為每次異動都要同步更新索引），需要在「查詢快」跟「異動快」之間取捨",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "兩個人同時在改同一筆銀行帳戶餘額，如果隔離等級設太寬鬆，最可能發生什麼問題？",
        options: [
          "其中一筆更新可能被覆蓋掉，或讀到還沒確定要不要生效的中間資料",
          "資料庫會自動排隊，完全不會有問題",
          "SQL 語法會直接報錯",
        ],
        correctIndex: 0,
        explanation: "隔離等級太寬鬆時，交易之間可能互相看到未提交的資料或發生更新遺失，這正是為什麼交易隔離等級的選擇很重要。",
      },
    ],
  },
  {
    id: "linux-advanced",
    title: "Linux 進階",
    stage: 6,
    tagline: "把一堆指令變成一個可以重複執行的小程式",
    notTaught: ["Kernel 原始碼層級除錯", "進階正規表示式（regex）撰寫", "SELinux/AppArmor 權限模組"],
    prerequisites: ["linux"],
    position: { x: 900, y: 780 },
    steps: [
      {
        type: "concept",
        title: "進階概念",
        bullets: [
          "Shell Script：把一連串指令寫進一個 .sh 檔案，一次執行，還可以加上變數、迴圈（for/while）、判斷式（if），是最基本的自動化工具",
          "常見用途：批次處理檔案、部署前的環境檢查，CI pipeline 裡跑的許多步驟背後其實就是 shell script",
          "核心（Kernel）：作業系統最核心的程式，負責管理硬體資源（CPU、記憶體、裝置），應用程式透過「系統呼叫」跟 kernel 溝通，一般開發不會直接碰但影響著系統效能與穩定性",
          "系統管理：例如使用者權限管理（useradd/usermod）、服務管理（systemctl start/stop/status）、排程工作（cron），是維運工程師的日常工作，也是 QA 排查測試環境問題時常用到的技能",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "想要「每天凌晨自動清空一次暫存資料夾」，最適合用下面哪種方式？",
        options: ["寫一個 shell script 搭配 cron 排程", "每天手動登入伺服器刪除", "改寫作業系統核心"],
        correctIndex: 0,
        explanation: "cron 是 Linux 內建的排程工具，搭配 shell script 就能讓固定的維護工作自動化執行，不需要人工介入。",
      },
    ],
  },
  {
    id: "docker-advanced",
    title: "Docker 進階",
    stage: 6,
    tagline: "一個房間不夠住，那就蓋一整個社區",
    notTaught: ["Kubernetes 完整資源物件（Deployment/Service/Ingress）", "Service Mesh", "跨雲端容器編排比較"],
    prerequisites: ["docker"],
    position: { x: 1200, y: 780 },
    steps: [
      {
        type: "concept",
        title: "進階概念",
        bullets: [
          "Docker Compose：用一份 YAML 檔案描述「系統需要哪幾個 container（例如 API、資料庫、快取）、怎麼串起來」，一個指令 docker compose up 就能把整組服務都啟動",
          "為什麼需要它：真實系統很少只有一個 container，手動一個個 docker run 很麻煩，Compose 讓多容器系統的啟動與設定變得簡單",
          "Kubernetes（K8s）：當 container 數量多到要跑在很多台機器上，需要有人幫忙「自動排班、自動重啟掛掉的 container、依流量自動調整數量」，Kubernetes 就是做這件事的「container 界的總管家」",
          "網路模式：container 之間預設互相隔離，要讓它們能互相溝通需要設定網路模式，Docker Compose 預設會幫同一組服務建立共用網路",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "一個系統包含 API、資料庫、快取三個 container，想要一個指令就把三個都啟動並互相連通，最適合用什麼？",
        options: ["Docker Compose", "手動對每個 container 各自下 docker run", "把三個功能寫進同一個 container"],
        correctIndex: 0,
        explanation: "Docker Compose 用一份設定檔描述多個 container 該怎麼一起啟動、怎麼互相溝通，是管理多容器系統最基本的工具。",
      },
    ],
  },
  {
    id: "rest-api-advanced",
    title: "RESTful API 進階",
    stage: 6,
    tagline: "菜單改版了，舊客人要不要看得懂？",
    notTaught: ["GraphQL Schema/Resolver 實作", "OAuth 各種 Grant Type 細節", "OpenID Connect"],
    prerequisites: ["rest-api"],
    position: { x: 1500, y: 780 },
    steps: [
      {
        type: "concept",
        title: "進階概念",
        bullets: [
          "API 版本控制：系統上線後功能會一直演進，但已經串接的舊客戶端不能說壞就壞，常見做法是網址帶版本號（/v1/books、/v2/books）或用 Header 指定版本，讓新舊版本並存一段時間",
          "GraphQL：跟 REST 不同的 API 設計方式，前端可以在一次請求裡自己指定要哪些欄位，避免拿到用不到的欄位或要打好幾次 API 才湊得齊資料，代價是後端設計與快取策略更複雜",
          "OAuth：一套「授權」標準流程，讓使用者可以說「我同意讓 A 服務代表我，去 B 服務拿有限的資料」而不用把密碼直接給 A 服務，常見的「用 Google 帳號登入」背後就是 OAuth",
          "Access Token / Refresh Token：Access Token 是短效期的通行證（過期要重新拿），Refresh Token 用來在不用重新輸入密碼的情況下換一張新的 Access Token",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "系統要推出重大改版，但很多舊客戶端還在用舊版 API，不能立刻切換，比較合理的做法是？",
        options: [
          "同時提供 /v1 和 /v2 兩個版本的 API，讓舊客戶端有緩衝期慢慢遷移",
          "直接關閉舊版 API，強迫大家馬上升級",
          "把新舊版本邏輯寫在同一個路由裡隨機回應",
        ],
        correctIndex: 0,
        explanation: "API 版本控制的目的就是讓新舊版本可以並存一段時間，避免舊客戶端在沒有準備好的情況下突然壞掉。",
      },
    ],
  },
  {
    id: "message-queue-advanced",
    title: "資料佇列進階",
    stage: 6,
    tagline: "一條排隊隊伍不夠快，那就開很多條櫃檯",
    notTaught: ["Kafka 內部儲存格式與 Replication 細節", "分散式共識演算法（Raft/Paxos）", "跨資料中心災難復原"],
    prerequisites: ["message-queue"],
    position: { x: 1800, y: 780 },
    steps: [
      {
        type: "concept",
        title: "進階概念",
        bullets: [
          "分區（Partition）：像 Kafka 這類系統會把一個 Topic（訊息類別）拆成多個 Partition，不同 Partition 可以被不同 Consumer 平行處理以提升吞吐量，但同一個 Partition 內的訊息順序才有保證",
          "訊息保證語意：常見有 At most once（可能漏送但不會重複）、At least once（保證送到但可能重複）、Exactly once（保證剛好一次，實作最複雜），要依業務需求選擇合適的語意",
          "叢集架構：為避免佇列系統本身變成單點故障，會用多台機器組成叢集互相備援，其中一台掛了其他台能接手，資料也會複製多份避免遺失",
          "這些是「當系統流量規模變大」才需要深入研究的主題，一開始學 MQ 概念（Producer/Consumer/Queue/ACK）已經足夠應付大部分場景",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "扣款這種「絕對不能重複扣兩次」的操作，訊息保證語意最需要注意什麼？",
        options: [
          "確保是 Exactly once，或用其他方式（如冪等設計）避免同一筆訊息被重複處理",
          "只要 At least once 就好，反正客戶不會發現",
          "不需要考慮這個問題，佇列會自動處理好",
        ],
        correctIndex: 0,
        explanation: "扣款這類操作如果被重複處理會造成實際金錢損失，因此需要 Exactly once 語意或在業務邏輯上做「冪等」設計（重複執行結果仍然一樣）。",
      },
    ],
  },
  {
    id: "test-case-design-advanced",
    title: "測試案例設計進階",
    stage: 6,
    tagline: "從「憑經驗抓漏洞」到「用方法論系統化找漏洞」",
    notTaught: ["特定形式化驗證工具（如 TLA+）操作", "TestRail/Zephyr 完整功能", "Model-Based Testing 工具鏈實作"],
    prerequisites: ["test-case-design"],
    position: { x: 0, y: 1040 },
    steps: [
      {
        type: "concept",
        title: "進階概念",
        bullets: [
          "形式化驗證方法（Formal Verification）：用數學方式證明程式（或規格）在所有情況下都符合預期行為，常見於航太、醫療等對正確性要求極高的領域，成本很高，一般商業軟體較少全面採用",
          "測試案例管理系統：像 TestRail、Zephyr 這類工具，用來集中管理大量測試案例、追蹤執行結果、產生涵蓋率報告，適合案例數量龐大、需要跨團隊協作的專案",
          "模型驅動測試（Model-Based Testing）：先建立系統行為的「模型」（例如狀態機），再用工具自動從模型產生大量測試案例，減少人工設計案例的負擔，但建模本身也需要一定學習成本",
          "這些工具與方法通常在案例規模、對正確性要求更高的專案中才會派上用場，先熟悉等價分割、邊界值、決策表這些基本技巧，就能應付大部分日常測試設計",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "一個航太系統對「絕對不能出錯」的要求極高，願意投入大量成本確保正確性，比較會採用下面哪種做法？",
        options: [
          "形式化驗證方法，用數學證明取代（或補強）大量測試",
          "只做等價分割與邊界值分析就足夠",
          "完全不需要測試，靠開發者自己小心",
        ],
        correctIndex: 0,
        explanation: "對正確性要求極端嚴格的系統，會考慮投入成本更高的形式化驗證方法，用數學證明來補強一般測試手法難以窮舉的情境。",
      },
    ],
  },
  {
    id: "bug-lifecycle-advanced",
    title: "缺陷管理進階",
    stage: 6,
    tagline: "罰單開出去之後，公司內部還有一整套規矩",
    notTaught: ["Jira/Zentao 工作流程細部設定", "契約與法務條款撰寫", "跨組織 Escalation Matrix 設計"],
    prerequisites: ["bug-lifecycle"],
    position: { x: 300, y: 1040 },
    steps: [
      {
        type: "concept",
        title: "進階概念",
        bullets: [
          "SLA（Service Level Agreement）：對「多嚴重的問題，最慢要在多久內回應/修復」的正式承諾，例如「Critical 等級的缺陷要在 4 小時內回應、24 小時內修復」，常見於企業對客戶的合約條款",
          "SLA 罰則：如果沒有在承諾時間內處理完，可能會有退費、賠償等契約後果，這也是為什麼 Severity/Priority 的判斷在有 SLA 的專案裡格外重要",
          "跨團隊流程治理：當一個缺陷牽涉到多個團隊（例如前端、後端、第三方廠商）時，需要有明確的「誰負責分派、誰負責追蹤、多久要升級（escalate）給主管」的治理規則，避免缺陷卡在團隊間互踢皮球",
          "工具操作細節（如 Jira 特定欄位、工作流程設定）因公司而異，核心觀念（狀態流轉、Severity/Priority）比死背特定工具操作更重要",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "合約規定「Critical 缺陷需在 4 小時內回應」，如果超過時間沒回應，對公司而言最直接的風險是什麼？",
        options: [
          "可能違反 SLA 造成賠償或信譽損失，即使問題最終有修好",
          "沒有任何影響，只要最後有修好就好",
          "客戶會自動理解並延長期限",
        ],
        correctIndex: 0,
        explanation: "SLA 是正式的服務承諾，即使問題最終被修復，若回應/修復時間超過合約約定，仍可能觸發罰則或影響客戶信任，這也是為什麼 Severity/Priority 判斷要謹慎。",
      },
    ],
  },
  {
    id: "api-testing-advanced",
    title: "API 測試進階",
    stage: 6,
    tagline: "測試不再只是手動點一次，而是每次提交都自動跑",
    notTaught: ["RestAssured 完整程式碼撰寫", "OWASP API Security Top 10 逐項實作", "GraphQL 查詢複雜度限制實作"],
    prerequisites: ["api-testing"],
    position: { x: 600, y: 1040 },
    steps: [
      {
        type: "concept",
        title: "進階概念",
        bullets: [
          "Collection Runner／Newman：Postman 可以把一整組請求存成 Collection，用 Collection Runner 依序自動執行；Newman 是它的命令列版本，能整合進 CI pipeline，讓每次提交程式碼都自動跑一次 API 測試",
          "RestAssured：Java 生態系常用的 API 測試框架，可以用程式碼（而非 GUI）描述請求與斷言，方便跟其他自動化測試程式碼放在一起維護、進版控",
          "API 安全測試基本概念：常見檢查項目包含「未授權的使用者能不能存取不該看到的資料（越權）」「輸入是否可能造成 SQL Injection／XSS」「Rate Limiting 是否有效防止暴力嘗試」",
          "GraphQL 測試：因為 GraphQL 允許前端自訂查詢欄位，測試時要特別注意「查詢深度是否有限制（避免惡意巢狀查詢拖垮伺服器）」「欄位權限控制是否正確」",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "團隊想要「每次有人 push 程式碼，就自動把整組 API 測試跑一遍」，比較適合用下面哪個做法？",
        options: [
          "把 Postman Collection 匯出，搭配 Newman 整合進 CI pipeline",
          "每次都手動開 Postman 點過一遍",
          "只在發版前手動測一次就好",
        ],
        correctIndex: 0,
        explanation: "Newman 是 Postman Collection 的命令列執行工具，能整合進 CI pipeline 達成自動化，符合「每次提交都驗證」的目標。",
      },
    ],
  },
  {
    id: "test-automation-advanced",
    title: "自動化測試進階",
    stage: 6,
    tagline: "機器人越用越多之後，怎麼讓它們不要打架",
    notTaught: ["Selenium/Playwright 完整 API 逐一介紹", "BrowserStack/Sauce Labs 實際操作", "進階 POM 變形（如 Screenplay Pattern）"],
    prerequisites: ["test-automation"],
    position: { x: 900, y: 1040 },
    steps: [
      {
        type: "concept",
        title: "進階概念",
        bullets: [
          "Selenium vs Playwright：Selenium 是最老牌、支援瀏覽器最廣的自動化框架；Playwright 是較新的框架，內建等待機制更聰明、執行速度通常更快，兩者都能操作瀏覽器模擬使用者點擊/輸入",
          "跨瀏覽器雲端服務：像 BrowserStack、Sauce Labs 這類服務，提供大量不同瀏覽器/作業系統版本的環境，讓團隊不用自己維護一堆實體/虛擬機器就能做跨瀏覽器測試",
          "Page Object Model（POM）：把「頁面上的元素定位」跟「測試案例邏輯」分開寫，每個頁面對應一個 Page Object 類別，頁面改版時只需要改 Page Object，不用一一修改每支測試案例",
          "隨著自動化案例數量增加，好的設計模式（如 POM）會決定「維護成本」是可控還是失控",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "登入頁面改版換了新的按鈕 CSS class，導致所有牽涉到登入的自動化測試都失敗，如果原本有用 Page Object Model，修復方式是？",
        options: [
          "只需要修改登入頁面對應的 Page Object 類別裡的定位方式，其他測試案例不用逐一修改",
          "要把每一支測試案例裡的定位程式碼都找出來改一次",
          "只能整套測試案例重寫",
        ],
        correctIndex: 0,
        explanation: "Page Object Model 把元素定位集中管理，頁面改版時只需要更新對應的 Page Object，所有使用到它的測試案例就會自動套用新的定位方式，這正是它的核心價值。",
      },
    ],
  },
  {
    id: "performance-testing-advanced",
    title: "效能測試進階",
    stage: 6,
    tagline: "光說「系統很慢」不夠，要能指出慢在哪裡",
    notTaught: ["JMeter/Gatling 逐行腳本撰寫", "New Relic/Datadog 深度設定", "容量規劃數學模型推導"],
    prerequisites: ["performance-testing"],
    position: { x: 1200, y: 1040 },
    steps: [
      {
        type: "concept",
        title: "進階概念",
        bullets: [
          "JMeter／Gatling：常見的壓力測試工具，可以錄製或撰寫腳本模擬大量使用者同時發請求，觀察系統在不同負載下的表現",
          "APM（Application Performance Monitoring）：像 New Relic、Datadog 這類監控工具，能追蹤一個請求在系統內部各環節（資料庫查詢、外部 API 呼叫等）各花了多少時間，幫助快速定位「慢在哪一段」，而不是只知道「整體很慢」",
          "容量規劃（Capacity Planning）：根據預期流量（例如「雙11預估十倍平常流量」），推算需要多少台伺服器、多少資料庫連線數，才能在不過度浪費資源的情況下撐住尖峰",
          "這些工具與模型通常在系統要準備迎接大流量事件（促銷活動、新產品發表）前，會被拿出來認真使用",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "效能測試發現「某個 API 回應變慢」，但不知道是資料庫查詢慢、還是呼叫的外部服務慢，這時候最需要什麼工具來定位問題？",
        options: [
          "APM（應用效能監控）工具，追蹤請求在各環節花費的時間",
          "只靠加大伺服器規格，不需要定位問題",
          "重新寫一次程式碼，用猜的方式除錯",
        ],
        correctIndex: 0,
        explanation: "APM 工具能拆解一個請求在系統內部各個環節（資料庫、外部 API、內部邏輯）各花了多少時間，是定位效能瓶頸最直接有效的方法，而不是憑感覺猜測。",
      },
    ],
  },
];

export const getTopic = (id: string) => topics.find((t) => t.id === id);
