import type { Topic } from "./types";

export const topics: Topic[] = [
  {
    id: "data-structure",
    title: "資料結構",
    stage: 0,
    tagline: "資料的「收納方式」——決定你找東西快不快",
    notTaught: ["時間複雜度 Big-O", "平衡樹細節", "演算法競賽技巧"],
    prerequisites: [],
    position: { x: 0, y: 0 },
    steps: [
      {
        type: "analogy",
        title: "比喻：收納方式",
        body: "資料結構就像家裡的收納方式——抽屜、櫃子、族譜樹，決定你找東西快不快。同一批東西，收納方式不同，找起來的速度天差地遠。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "陣列 / 清單：一排編號的置物櫃，依號碼找東西",
          "Key-Value：貼標籤的箱子，例如字典，用「名字」找內容",
          "樹狀結構：家族族譜、資料夾巢狀結構，一層包一層",
          "為什麼「結構選對」查詢會變快：翻書 vs 翻字典的差別",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "如果你要做一本「通訊錄」，用姓名快速查電話，比較適合用哪種收納方式？",
        options: ["按登記順序排的清單", "用姓名當標籤的 Key-Value", "沒有規則的散亂堆放"],
        correctIndex: 1,
        explanation: "用姓名當 Key 直接對應到電話，就像字典一樣可以快速查到，不用整本翻過一遍。",
      },
    ],
  },
  {
    id: "networking",
    title: "網路傳輸",
    stage: 0,
    tagline: "兩台電腦怎麼「對話」？",
    notTaught: ["TCP 三向交握細節", "OSI 七層模型全部背誦", "封包格式"],
    prerequisites: [],
    position: { x: 0, y: 260 },
    steps: [
      {
        type: "analogy",
        title: "比喻：打電話",
        body: "兩台電腦對話就像兩個人打電話——要有「電話號碼」（IP）、「分機」（Port），還要講同一種語言（協定），對方才聽得懂。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "IP：電腦在網路上的地址",
          "Port：同一台電腦裡，不同服務的「分機號碼」",
          "Client-Server：誰先開口發請求、誰負責回應",
          "HTTP 是一種「對話規則」，不是網路本身",
          "TCP（掛號信，保證送達）vs UDP（普通信，快但不保證）",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "網址 http://example.com:8080 裡的「8080」代表什麼？",
        options: ["網站的密碼", "分機號碼（Port）", "檔案的版本號"],
        correctIndex: 1,
        explanation: "8080 是 Port，代表要連到這台主機上「哪一個服務」，就像打電話轉分機一樣。",
      },
    ],
  },
  {
    id: "sql",
    title: "SQL / 資料庫",
    stage: 1,
    tagline: "一個很會整理的 Excel 系統",
    notTaught: ["正規化理論", "交易隔離等級", "索引優化細節"],
    prerequisites: ["data-structure"],
    position: { x: 300, y: 0 },
    steps: [
      {
        type: "analogy",
        title: "比喻：進階版 Excel",
        body: "資料庫就是「一個很會整理的 Excel 系統」，SQL 是你跟它下指令的語言，讓它幫你新增、查詢、修改、刪除資料。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "Table / 欄位 / 資料列：就是進階版的 Excel 表格",
          "CRUD：新增（INSERT）、查詢（SELECT）、修改（UPDATE）、刪除（DELETE）",
          "主鍵：每個人的身分證字號，不會重複，用來認出「是哪一列」",
          "表格關聯 JOIN：訂單表 連到 客戶表，把兩張表格「拼」在一起看",
          "GROUP BY / COUNT：分組統計，例如「每個客戶各下了幾張訂單」",
          "NULL：代表「沒有值」，跟空字串或 0 不一樣，QA 測試資料缺漏時常會遇到",
        ],
      },
      {
        type: "sql-sandbox",
        title: "動手試試：真的跑一次 SQL",
        body: "下面切換不同情境練習：書店庫存的基本查詢、訂單與客戶的跨表 JOIN，以及專門給 QA 練習的邊界值／NULL 情境。",
      },
      {
        type: "quiz",
        title: "小驗收 1：基本查詢",
        question: "想要「查出所有書名」，該用哪個指令開頭？",
        options: ["SELECT", "INSERT", "DELETE"],
        correctIndex: 0,
        explanation: "SELECT 用來查詢資料，INSERT 是新增、DELETE 是刪除。",
      },
      {
        type: "quiz",
        title: "小驗收 2：跨表查詢情境",
        question: "在「訂單與客戶」情境中，想要同時顯示「客戶姓名」和「訂了哪本書」，因為這兩個欄位分別在 customers 和 orders 兩張表格裡，該用哪個關鍵字把它們接起來？",
        options: ["JOIN", "GROUP BY", "LIMIT"],
        correctIndex: 0,
        explanation: "JOIN 可以依照關聯欄位（例如 customer_id）把兩張表格的資料「拼」在一起查詢。",
      },
      {
        type: "quiz",
        title: "小驗收 3：QA 邊界值情境",
        question: "在「邊界值與 NULL」情境中，如果規格寫「年齡必須大於等於 18 歲」，身為 QA 最應該優先測試的資料是哪一筆？",
        options: [
          "年齡 = 30（明顯合法的一般值）",
          "年齡 = 18（剛好卡在規則邊界上）",
          "年齡 = 999（明顯超出常理的極端值）",
        ],
        correctIndex: 1,
        explanation: "邊界值分析告訴我們，規則的「邊界」（這裡是剛好等於 18）最容易因為程式寫成 > 而不是 >= 而出現 bug，是 QA 測試的重點。",
      },
    ],
  },
  {
    id: "linux",
    title: "Linux",
    stage: 2,
    tagline: "另一種作業系統，只是改用打字下指令",
    notTaught: ["Shell script 進階語法", "核心（kernel）原理", "系統管理"],
    prerequisites: [],
    position: { x: 300, y: 260 },
    steps: [
      {
        type: "analogy",
        title: "比喻：打字版的檔案總管",
        body: "Linux 就是「另一種作業系統」，沒有滑鼠點點點，改用打字下指令。Terminal 就是「打字版的檔案總管」。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "為什麼工程師常用 Linux：伺服器幾乎都跑 Linux",
          "基本指令：ls（列出檔案）、cd（切換資料夾）、pwd（目前在哪）、cat（看檔案內容）、mkdir（新增資料夾）",
          "檔案權限：誰可以看 / 改 / 執行，用「鑰匙」比喻",
        ],
      },
      {
        type: "linux-sandbox",
        title: "動手試試：模擬終端機",
        body: "下面是一個模擬的終端機，已經幫你準備好 /home/user 底下的檔案。試著用指令探索看看。",
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "指令 mkdir project && cd project 在做什麼？",
        options: [
          "刪除 project 資料夾",
          "新增一個叫 project 的資料夾，然後切換進去",
          "列出 project 資料夾內容",
        ],
        correctIndex: 1,
        explanation: "mkdir 新增資料夾，&& 代表「前一步成功才繼續」，cd 是切換進去該資料夾。",
      },
    ],
  },

  {
    id: "docker",
    title: "Docker",
    stage: 2,
    tagline: "隨身攜帶的完整房間",
    notTaught: ["Docker Compose 進階編排", "Kubernetes", "網路模式細節"],
    prerequisites: ["linux"],
    position: { x: 600, y: 260 },
    steps: [
      {
        type: "analogy",
        title: "比喻：隨身攜帶的房間",
        body: "Docker 就是「隨身攜帶的完整房間」——不管搬到誰的電腦，房間裡的擺設（環境）都一樣，不會出現「在我電腦可以跑，換一台就壞掉」的問題。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "為什麼需要它：解決「環境不一致」的痛點",
          "Image：房間的設計圖（不會變動）",
          "Container：真的蓋出來、正在運作的房間",
          "常用指令：docker run（蓋房間並住進去）、docker ps（看有哪些房間在運作）、docker stop（把房間關掉）",
          "Dockerfile：蓋房間的施工說明書",
        ],
      },
      {
        type: "docker-visual",
        title: "圖解：從 Dockerfile 到 Container",
        body: "點下面每個方塊看說明，也可以展開「有沒有 Docker」的比較圖。",
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "Image 跟 Container 的差別，比較接近下面哪一個說法？",
        options: [
          "Image 是設計圖，Container 是照圖蓋出來、正在運作的房間",
          "兩者是同一件事，只是名字不同",
          "Container 是設計圖，Image 是蓋好的房間",
        ],
        correctIndex: 0,
        explanation: "Image 不會變動，是「藍圖」；Container 是根據 Image 實際跑起來的實體。",
      },
    ],
  },
  {
    id: "rest-api",
    title: "RESTful API",
    stage: 3,
    tagline: "餐廳菜單——照著點餐，廚房就會出餐",
    notTaught: ["GraphQL", "API 版本控制策略", "OAuth 完整規格"],
    prerequisites: ["networking", "sql"],
    position: { x: 600, y: 0 },
    steps: [
      {
        type: "analogy",
        title: "比喻：餐廳菜單",
        body: "API 就是「餐廳菜單」——你不用進廚房，只要照著菜單點餐（發請求），廚房就會出餐（回應資料）。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "Request / Response：請求要有方法、網址、資料；回應會有結果",
          "GET / POST / PUT / DELETE 對應「查、增、改、刪」，跟 SQL 的 CRUD 是同一件事的不同說法",
          "Status Code：200（成功）、404（找不到）、500（伺服器出錯），像服務生的回覆",
          "JSON：資料的共同語言格式，讓不同系統都看得懂",
        ],
      },
      {
        type: "api-sandbox",
        title: "動手試試：呼叫一個模擬 API",
        body: "下面是一個「書店 API」，新增／修改／刪除都會真的改動資料（不是假的），操作後可以再查一次全部書籍確認結果。",
      },
      {
        type: "quiz",
        title: "小驗收 1",
        question: "呼叫 API 後收到 Status Code 404，代表什麼？",
        options: ["請求成功", "找不到你要的資源", "伺服器內部發生錯誤"],
        correctIndex: 1,
        explanation: "404 代表「找不到」，通常是網址或資源 ID 不存在；500 才是伺服器自己出錯。",
      },
      {
        type: "quiz",
        title: "小驗收 2：驗證資料真的變了",
        question: "呼叫 POST /books 新增一本書後，收到 Status 201 且回應內容看起來正確，身為 QA 接下來最應該做什麼？",
        options: [
          "相信回應內容就好，不用再確認",
          "再呼叫一次 GET /books，確認新資料真的被存起來、筆數真的增加",
          "直接判斷這支 API 沒有問題並結案",
        ],
        correctIndex: 1,
        explanation: "API 的回應只代表「伺服器說它做了」，QA 測試時應該再查詢一次驗證資料確實被持久化，這是很多真實 bug（回應成功但資料沒真的寫入）會被抓到的關鍵習慣。",
      },
    ],
  },
  {
    id: "message-queue",
    title: "資料佇列 / MQ",
    stage: 4,
    tagline: "銀行的排隊叫號機",
    notTaught: ["Kafka 分區機制", "訊息保證語意細節", "叢集架構"],
    prerequisites: ["rest-api", "docker"],
    position: { x: 900, y: 130 },
    steps: [
      {
        type: "analogy",
        title: "比喻：排隊叫號機",
        body: "資料佇列就是「銀行的排隊叫號機」——客人（請求）不用一直站著等櫃檯處理完，先抽號碼牌，系統會照順序慢慢處理。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "為什麼需要它：同步請求太慢、系統忙不過來時的解法",
          "Producer（發號碼牌的人）/ Consumer（櫃檯）/ Queue（排隊隊伍）",
          "「非同步」：先做別的事，等通知再回來處理",
          "ACK（確認收到）：Consumer 處理完要跟佇列回報一聲，佇列才會真的刪掉這則訊息",
          "常見場景：訂單處理、寄送通知信",
        ],
      },
      {
        type: "mq-visual",
        title: "圖解：排隊動畫",
        body: "連續按幾次「送出新請求」，看看號碼牌怎麼排隊、怎麼被一個一個處理掉。",
      },
      {
        type: "mq-failure-visual",
        title: "圖解：Consumer 突然掛掉，訊息會不見嗎？",
        body: "一步一步看：處理到一半的 Consumer 當機了，佇列怎麼確保這則訊息還是會被處理完成，不會憑空消失。",
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "網路購物「付款後立刻跳成功頁面，出貨通知信晚點才寄到」，比較像哪種模式？",
        options: ["同步，馬上處理完才給結果", "非同步排隊，之後再慢慢處理", "沒有任何處理"],
        correctIndex: 1,
        explanation: "付款結果馬上給你，但寄信這種「不急著馬上完成」的事會被丟進佇列，之後再慢慢處理。",
      },
    ],
  },
  {
    id: "test-case-design",
    title: "測試案例設計",
    stage: 5,
    tagline: "把「憑感覺測」變成「有系統地測」",
    notTaught: ["形式化驗證方法", "測試案例管理系統操作細節", "模型驅動測試工具鏈"],
    prerequisites: [],
    position: { x: 0, y: 520 },
    steps: [
      {
        type: "analogy",
        title: "比喻：衣服的尺碼表",
        body: "衣服不會每個身高、體重都做一件，而是分成 S / M / L 幾個「等價」的區間，各區間內隨便挑一個人試穿都差不多準。測試案例設計也一樣：與其把每種輸入都測一遍，不如先把輸入分類，每一類挑代表性的值，並特別留意「剛好卡在分類邊界」的那幾件。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "等價分割（Equivalence Partitioning）：把輸入依「行為是否相同」分組，每組只需測一個代表值",
          "邊界值分析（Boundary Value Analysis）：規則的邊界（剛好等於、剛好差一）最容易寫錯，例如 >= 18 寫成 > 18",
          "決策表（Decision Table）：當有多個條件互相組合時，用表格列出「條件組合 → 應該發生的結果」，避免漏掉某種組合",
          "Given-When-Then：用「情境 / 動作 / 結果」描述一個案例，讓不懂程式的人也能看懂測試在驗證什麼",
        ],
      },
      {
        type: "quiz",
        title: "小驗收 1：邊界值",
        question: "系統規則是「訂單金額滿 1000 元免運費」，用邊界值分析，最值得測試的金額組合是？",
        options: [
          "500 元、5000 元（一個很小、一個很大）",
          "999 元、1000 元、1001 元（剛好卡在邊界前後）",
          "只測 1000 元一種就夠了",
        ],
        correctIndex: 1,
        explanation: "999、1000、1001 剛好涵蓋「差一點沒到」「剛好達到」「超過」三種邊界情況，最容易抓出 > 寫成 >= 之類的錯誤。",
      },
      {
        type: "quiz",
        title: "小驗收 2：等價分割",
        question: "一個欄位規定「只能輸入 1~100 的整數」，下面哪一組測試資料最符合「等價分割」的精神？",
        options: [
          "1, 2, 3, 4, 5……一路測到 100（每個數字都測）",
          "50（合法區間的代表值）、0（太小）、101（太大）、abc（非數字）",
          "只測一個 50 就結束",
        ],
        correctIndex: 1,
        explanation: "等價分割是每種「類別」各挑一個代表值：合法範圍內、小於下限、大於上限、格式錯誤，四個代表值就能涵蓋主要情境，不需要窮舉每個數字。",
      },
    ],
  },
  {
    id: "bug-lifecycle",
    title: "缺陷生命週期與管理",
    stage: 5,
    tagline: "一張罰單從開單到結案的旅程",
    notTaught: ["特定工具（Jira/Zentao）操作介面細節", "SLA 罰則計算", "跨團隊流程治理制度"],
    prerequisites: [],
    position: { x: 300, y: 520 },
    steps: [
      {
        type: "analogy",
        title: "比喻：一張罰單的旅程",
        body: "回報一個 bug 就像開一張罰單：先「開單」記錄現場（重現步驟），交給對的人「處理」，處理完要有人「驗證」真的改好了才能「結案」；如果驗證沒過，罰單會被「退回」重開一輪，不是隨便關掉就算了。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "缺陷狀態流轉：New（新開） → In Progress（處理中） → Resolved（已修復） → Verified/Closed（驗證通過關閉）或 Reopened（驗證沒過，退回重修）",
          "Severity（嚴重程度）：這個 bug 造成的影響有多嚴重（例如系統當機 vs 文字對不齊）",
          "Priority（優先權）：這個 bug 該多快被處理（可能嚴重度不高，但影響到重要客戶，優先權就拉高）",
          "重現步驟（Repro Steps）：清楚寫出「怎麼操作會發生」，是 bug 能不能被修好的關鍵，比一句「壞了」有用一百倍",
          "為什麼要記錄環境資訊：同一個 bug 可能只在特定瀏覽器、特定資料狀態下才會出現",
        ],
      },
      {
        type: "quiz",
        title: "小驗收 1：Severity vs Priority",
        question: "「登入頁面某個按鈕的文字對齊有 2px 的小誤差，但這個功能是本週要展示給重要客戶看的」，這種情況比較符合下面哪種分類？",
        options: [
          "Severity 高、Priority 高",
          "Severity 低、Priority 高",
          "Severity 高、Priority 低",
        ],
        correctIndex: 1,
        explanation: "這個瑕疵本身對系統功能影響很小（Severity 低），但因為時機敏感、需要盡快修（Priority 高），這正是 Severity 跟 Priority 會不一致的典型例子。",
      },
      {
        type: "quiz",
        title: "小驗收 2：驗證與 Reopen",
        question: "開發說某個 bug 已經修好並改成 Resolved，QA 重新測試後發現在特定情況下問題還是會發生，接下來該怎麼做？",
        options: [
          "直接把狀態改成 Closed，反正大部分情況都正常了",
          "把狀態改回 Reopened，並補充「還會發生問題」的具體重現條件",
          "自己私下修掉就好，不需要更新狀態",
        ],
        correctIndex: 1,
        explanation: "驗證沒通過就該 Reopen，並且補上新的重現條件讓開發知道差在哪裡，狀態要誠實反映真實情況，才能讓整個團隊追蹤進度。",
      },
    ],
  },
  {
    id: "api-testing",
    title: "API 測試實務",
    stage: 5,
    tagline: "試菜員不只吃合格套餐，也要故意點奇怪組合",
    notTaught: ["特定工具（Postman/RestAssured）完整語法", "API 安全滲透測試細節", "GraphQL 測試"],
    prerequisites: ["rest-api"],
    position: { x: 600, y: 520 },
    steps: [
      {
        type: "analogy",
        title: "比喻：試菜員",
        body: "API 測試就像餐廳的試菜員——不能只點菜單上寫好的正常套餐（正向案例），還要故意點「沒有的菜」「數量填負的」「不付錢就要出餐」，看廚房會不會端出奇怪的東西，或至少要有禮貌地說「做不到」（正確的錯誤回應），而不是當場爆炸（500 錯誤、系統當機）。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "正向案例（Happy Path）：照規格正常操作，應該要成功",
          "反向案例（Negative Case）：故意給錯誤的輸入（缺欄位、型別錯、超出範圍），驗證系統有沒有「優雅地拒絕」而不是壞掉",
          "驗證重點不只是 Status Code：回應的 Schema（欄位有沒有齊全、型別對不對）、回應時間、資料是否真的被寫入，都是驗證項目",
          "契約測試（Contract Testing）：確保 API 的輸入輸出格式跟前端 / 其他服務約定的規格一致，避免「後端改格式，前端就壞掉」",
          "Mock Server：當依賴的第三方 API 還沒好、或不想每次測試都打真實服務時，用假伺服器模擬固定的回應",
        ],
      },
      {
        type: "api-sandbox",
        title: "動手試試：用 QA 的角度操作這支 API",
        body: "試著故意送出不合法的 body（例如缺少 title、stock 給字串），觀察 API 有沒有回傳正確的 400 錯誤，而不是直接壞掉或吃掉錯誤資料。",
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "測試「新增書籍」的 API 時，下面哪一個比較屬於「反向案例」？",
        options: [
          "帶正確的 title 和 stock，預期成功新增",
          "完全不帶 title 欄位，預期收到 400 且清楚的錯誤訊息",
          "查詢一本已存在的書，預期回傳該書資料",
        ],
        correctIndex: 1,
        explanation: "反向案例是刻意給不合法或不完整的輸入，重點在驗證系統有沒有「正確地拒絕」，而不是驗證正常流程。",
      },
    ],
  },
  {
    id: "test-automation",
    title: "自動化測試與 CI 整合",
    stage: 5,
    tagline: "請一個不會累的機器人幫你重複跑迴歸測試",
    notTaught: ["特定框架（Selenium/Playwright）完整 API", "跨瀏覽器雲端服務比較", "Page Object 進階設計模式"],
    prerequisites: ["api-testing", "docker"],
    position: { x: 900, y: 520 },
    steps: [
      {
        type: "analogy",
        title: "比喻：不會累的機器人",
        body: "自動化測試就像請一個不會累、不會分心、不會抱怨「這個流程我已經點過一百次了」的機器人，每次程式一有變動，就把該重複驗證的流程整套跑一遍，人力則專心去找機器人還想不到的奇怪情境。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "什麼案例適合自動化：會被重複執行、步驟穩定、驗證高風險核心流程的案例；一次性或常常改版的畫面不一定划算",
          "測試金字塔：Unit（單元測試）數量最多、跑最快；Integration（整合測試）居中；E2E（端對端）數量最少、跑最慢但最貼近真實使用情境",
          "CI/CD 整合：每次有人提交程式碼，管線（Pipeline）就自動跑一次測試，及早發現問題，不用等到快發版才手動測",
          "Flaky Test（不穩定測試）：同樣的程式碼，測試有時候過、有時候沒過，通常是等待時間沒抓好或測試之間互相影響，是自動化測試最惱人的問題之一",
        ],
      },
      {
        type: "quiz",
        title: "小驗收 1：測試金字塔",
        question: "測試金字塔的概念建議，一個健康的測試組合應該長怎樣？",
        options: [
          "大量的 E2E 測試，少量的單元測試",
          "大量的單元測試打底，少量但關鍵的 E2E 測試在最上層",
          "只需要 E2E 測試，其他都不需要",
        ],
        correctIndex: 1,
        explanation: "單元測試跑得快、成本低，適合大量覆蓋細節邏輯；E2E 測試貼近真實情境但跑得慢、維護成本高，只留給最關鍵的核心流程。",
      },
      {
        type: "quiz",
        title: "小驗收 2：Flaky Test",
        question: "同一支自動化測試，同樣的程式碼，這次跑過、下次跑失敗，重跑幾次又過了，這種情況最可能是什麼問題？",
        options: [
          "程式碼一定有 bug，且很嚴重",
          "測試本身不穩定（Flaky），可能是等待時間沒設好或測試互相干擾",
          "這是正常現象，不用理它",
        ],
        correctIndex: 1,
        explanation: "結果忽好忽壞、跟程式碼變動無關，通常代表測試本身「不穩定」，需要找出根本原因（例如非同步等待、測試資料污染），而不是單純重跑到過為止。",
      },
    ],
  },
  {
    id: "performance-testing",
    title: "效能測試",
    stage: 5,
    tagline: "尖峰時段的排隊名店，能撐住多少人潮？",
    notTaught: ["JMeter/Gatling 完整腳本語法", "APM 工具深度設定", "容量規劃精算模型"],
    prerequisites: ["message-queue"],
    position: { x: 1200, y: 260 },
    steps: [
      {
        type: "analogy",
        title: "比喻：排隊名店的尖峰時段",
        body: "效能測試就像故意在店家「平常」「特別多人的尖峰時段」「突然湧入一大群人」時，分別去觀察它能不能撐住——出餐會不會變慢、會不會直接當機、人潮退去後能不能恢復正常。",
      },
      {
        type: "concept",
        title: "核心概念",
        bullets: [
          "負載測試（Load Testing）：模擬「平常」預期的使用量，確認系統穩定運作",
          "壓力測試（Stress Testing）：不斷加大流量，直到系統撐不住為止，找出系統的極限在哪",
          "尖峰測試（Spike Testing）：模擬流量突然暴增（例如搶購活動），觀察系統反應",
          "耐久測試（Soak Testing）：長時間維持一定負載，抓「跑久了才會出現」的問題，例如記憶體洩漏",
          "常見指標：回應時間（Response Time）、吞吐量（Throughput，單位時間處理幾筆）、錯誤率（Error Rate）",
          "瓶頸可能藏在哪裡：應用程式本身、資料庫查詢、網路頻寬，或是訊息佇列堆積來不及消化",
        ],
      },
      {
        type: "quiz",
        title: "小驗收",
        question: "電商平台想知道「雙11搶購開賣那一秒瞬間湧入十倍平常流量，系統會不會撐不住」，這比較接近哪一種效能測試？",
        options: ["耐久測試（Soak Testing）", "尖峰測試（Spike Testing）", "只需要一般的功能測試"],
        correctIndex: 1,
        explanation: "「瞬間暴增」的流量情境正是尖峰測試要驗證的重點，跟耐久測試（長時間穩定負載）觀察的問題不一樣。",
      },
    ],
  },
];

export const getTopic = (id: string) => topics.find((t) => t.id === id);
